### PR TITLE
Fix #1 - Added to book1 and created book2

### LINKED ISSUE #1: Books_Issue1
Add your name to book1
Create  book2 file
Add your name to book2

### PR DESCRIPTION
**Pull request by joseluisbodi**
Hi 'all!
I've managed to finish this Books Issue 1 thing.
Please, check it out and approve the changes if they please you.
Thanks!

Now, just for the sake of trying this markdown thing I'll tell you how I did it with this screen capture that follows:
captura-subida

PD: @luz-abastos I don't know whether it is important or not but please notice the username I've done this exercise with. It is "joseluis-daw" instead of "ubuntu".

### CODE REVIEW

**Comment by aplicacionesgranotero** [comment]
Everything seems correct, I give you my approval.

**Review by aplicacionesgranotero — APPROVED** [review]

**Comment by joseluisbodi** [comment]
Now that the changes on my branch have been approved a merge pull request button is enabled for me to push.
Although the system is allowing me to merge this branch of mine it is up to another user merging the pull request not me. Am I right? That is, should I wait for Luz (for example) to finally merge this branch into the main one or should I do it myself?

**Comment by joseluisbodi** [comment]
Had to resolve a conflict in Books/book2. The main branch changed before my pull request was merged and this conflict emerged. Rewrote this Books/book2

**Comment by Sr-L** [comment]
I thik this is ok. Well done Jose

**Comment by joseluisbodi** [comment]
Thank you very much for your collaboration!! The merging is done!

**Pull request merged**
